language: python

python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE ROLE mitch with createdb login password 'mufasa2019'" postgres
  - psql -c "CREATE DATABASE questioner owner mitch" postgres
script: 
  - pytest --with-coverage --cover-package=app tests/
  - coveralls
branches:
  - develop

after_success:
  - coveralls

cache: pip