language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - python -m pytest --cov-report term-missing --cov=app
  -coveralls
branches:
  -develop

after_success:
  - coveralls

cache: pip