language: python

python:
  - "3.6.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - python -m pytest --cov-report term-missing --cov=app
  - coveralls
  - pytest
branches:
  - develop

after_success:
  - coveralls

cache: pip